snippets/custom-overrides: android_frameworks_native rev fece757
Using the latest commits from 2025 causes ABI mismatch problems when
compiling halium-11/lineage-18.1

This change uses the last known working (for me!) commit from the
lineage-18.1 upstream.

- commit id: fece757289f2605af7cce893e22856192a8936f3
- commit name: Merge tag 'android-security-11.0.0_r71' of https://android.googlesource.com/platform/frameworks/native into staging/lineage-18.1_merge_android-security-11.0.0_r71

Fixes error:
[ 89% 61020/67821] //frameworks/native/libs/binder:liFAILED: out/soong/.intermediates/frameworks/native/libs/binder/libbinder/android_vendor.30_arm64_armv8-a_shared/libbinder.so.abidiff
(prebuilts/clang-tools/linux-x86/bin/header-abi-diff -allow-unreferenced-changes -allow-unreferenced-elf-symbol-changes -lib libbinder -arch arm64 -o out/soong/.intermediates/frameworks/native/libs/binder/libbinder/android_vendor.30_arm64_armv8-a_shared/libbinder.so.abidiff -new out/soong/.intermediates/frameworks/native/libs/binder/libbinder/android_vendor.30_arm64_armv8-a_shared/libbinder.so.lsdump -old prebuilts/abi-dumps/vndk/30/64/arm64_armv8-a/source-based/libbinder.so.lsdump)|| (echo 'error: Please update ABI references with: $ANDROID_BUILD_TOP/development/vndk/tools/header-checker/utils/create_reference_dumps.py  -l libbinder' && (mkdir -p $DIST_DIR/abidiffs && cp out/soong/.intermediates/frameworks/native/libs/binder/libbinder/android_vendor.30_arm64_armv8-a_shared/libbinder.so.abidiff $DIST_DIR/abidiffs/) && exit 1)
******************************************************
error: VNDK library: libbinder's ABI has INCOMPATIBLE CHANGES Please check compatibility report at: out/soong/.intermediates/frameworks/native/libs/binder/libbinder/android_vendor.30_arm64_armv8-a_shared/libbinder.so.abidiff
******************************************************
error: Please update ABI references with: $ANDROID_BUILD_TOP/development/vndk/tools/header-checker/utils/create_reference_dumps.py  -l libbinder
16:41:51 ninja failed with: exit status 1

Signed-off-by: berbascum <berbascum@ticv.cat>